### ISSUE TITLE
Implement the pin drive capability

### ISSUE THREAD

**Issue by cicciocb** [cicciocb/Annex32_examples#21]
This is a feature available for the ESP32

typedef enum {
    GPIO_DRIVE_CAP_0       = 0,    /*!< Pad drive capability: weak          */
    GPIO_DRIVE_CAP_1       = 1,    /*!< Pad drive capability: stronger      */
    GPIO_DRIVE_CAP_2       = 2,    /*!< Pad drive capability: medium */
    GPIO_DRIVE_CAP_DEFAULT = 2,    /*!< Pad drive capability: medium */
    GPIO_DRIVE_CAP_3       = 3,    /*!< Pad drive capability: strongest     */
    GPIO_DRIVE_CAP_MAX,
} gpio_drive_cap_t;

/*Set GPIO pad drive capability */
gpio_set_drive_capability((gpio_num_t)pin, (gpio_drive_cap_t)value );

**Comment by cicciocb** [comment]
Implemented the function 

PIN.STRENGTH pin_nb, drive_cap

**Comment by DB9JG** [comment]
This feature could be the very last resort for a hardware issue with an ESP32 driving a peripheral component that needs unexpected amount of current

**Comment by cicciocb** [comment]
This has been implemented in the version 1.53.3.
In fact I found the interest into implementing this feature for exactly the opposite reason.
The reason ? The noise, a pin with too much strength that carries an high frequency signal generates a lot of EMI, in particular on the board itself. 
I found this issue when I designed a PCB for the VGA, solved reducing the strength from 2 (the default) to 0

**Comment by DB9JG** [comment]
Well, that is interesting indeed! 
I'll have to keep that in mind for future layouts and/or possible talkover between parallel wires. 
Thanks!

**Comment by DB9JG** [comment]
Forgot to introduce myself: DB9JG==PeterN
But I guess you already knew :-))

**Comment by cicciocb** [comment]
Implemented the function in the version 1.53.3

PIN.STRENGTH pin_nb, drive_cap

**Comment by cicciocb** [comment]
The help must be updated
